
public class SourceFile{

	String[]department=new String[]
			{"PersonalBanking&Operations",
			"DigitalBankingDepartment",
			"RetailBanking&MarketingDepartment",
			"WealthManagement&ThirdPartyProducts",
			"InternationalBankingDivision&DFB",
			"Treasury",
			"InformationTechnology",
			"CorporateCommunications",
			"SupportServices&BranchExpansion",
			"HumanResources",
			"LargeCorporate&LoanSyndication",
			"MSME(MicroSmall&MediumEnterprises)",
			"Rural&AgriBusiness",
			"FinancialInclusion",
			"LawDepartment",
			"CreditRecoveryDepartment",
			"RiskManagementDepartment",
			"CentralAudit&InspectionDepartment",
			"CreditMonitoringandRestructuringDepartment",
			"ComplianceDepartment",
			"BusinessProcessTransformation",
			"CentralAccounts&FPIR",
			"Govt.BusinessDept."};

	String[]subDepartment=new String[]{
			"PublicAccountsDepartment",
			"PublicDebtDepartment",
			"DepositAccountsDepartment",
			"SecuritiesDepartment",
			"RetailBanking",
			"Corporate/CommercialBanking",
			"GlobalBanking",
			"PrivateBanking",
			"InvestmentBanking",
			"Linesofcredit",
			"Investmentmanagementandaccounts",
			"Insurance",
			"Retirementandeducationaccounts",
			"Multi-currencymanagementservicesandproducts",
			"Foreigncurrencyaccounts",
			"Foreigncurrencycreditcards",
			"Transborderadvisoryservices",
			"Liquiditymanagement",
			"BankFinancialStatements",
			"BulgeBracketBanks",
			"BoutiqueInvestmentBanks",
			"Cryptocurrency"};
			
			
	String[] streatNames=new String[]{
			"Second Streat",
			"Third Streat",
			"First Streat",
			"Fourth Streat",
			"Park Streat",
			"Fifth Streat",
			"Main Streat",
			"Sixth Streat",
			"Oak Streat",
			"Seventh Streat",
			"Pine Streat",
			"Maple Streat",
			"Cedar Streat",
			"Eighth Streat",
			"Elm Streat",
			"View Streat",
			"Washington Streat",
			"Ninth Streat",
			"Lake Streat",
			"Hill Streat"	
			};
	
	String[]town=new String[]{
			"Albany",
			"Amsterdam",
			"Auburn",
			"Babylon",
			"Batavia",
			"Beacon",
			"Bedford",
			"Binghamton",
			"Bronx",
			"Brooklyn",
			"Buffalo",
			"Chautauqua",
			"Cheektowaga",
			"Clinton",
			"Cohoes",
			"ConeyIsland",
			"Cooperstown",
			"Corning",
			"Cortland",
			"CrownPoint",
			"Dunkirk",
			"EastAurora",
			"EastHampton",
			"Eastchester",
			"Elmira",
			"Flushing",
			"ForestHills",
			"Fredonia",
			"GardenCity",
			"Geneva",
			"GlensFalls",
			"Gloversville",
			"GreatNeck",
			"Hammondsport",
			"Harlem",
			"Hempstead",
			"Herkimer",
			"Hudson",
			"Huntington",
			"HydePark",
			"Ilion",
			"Ithaca",
			"Jamestown",
			"Johnstown",
			"Kingston",
			"Lackawanna",
			"LakePlacid",
			"Levittown",
			"Lockport",
			"Mamaroneck",
			"Manhattan",
			"Massena",
			"Middletown",
			"Mineola",
			"MountVernon",
			"NewPaltz",
			"NewRochelle",
			"NewWindsor",
			"NewYorkCity",
			"Newburgh",
			"NiagaraFalls",
			"NorthHempstead",
			"Nyack",
			"Ogdensburg",
			"Olean",
			"Oneida",
			"Oneonta",
			"Ossining",
			"Oswego",
			"OysterBay",
			"Palmyra",
			"Peekskill",
			"Plattsburgh",
			"PortWashington",
			"Potsdam",
			"Poughkeepsie",
			"Queens",
			"Rensselaer",
			"Rochester",
			"Rome",
			"Rotterdam",
			"Rye",
			"SagHarbor",
			"SaranacLake",
			"SaratogaSprings",
			"Scarsdale",
			"Schenectady",
			"SenecaFalls",
			"Southampton",
			"StatenIsland",
			"StonyBrook",
			"StonyPoint",
			"Syracuse",
			"Tarrytown",
			"Ticonderoga",
			"Tonawanda",
			"Troy",
			"Utica",
			"Watertown",
			"Watervliet",
			"WatkinsGlen",
			"WestSeneca",
			"WhitePlains",
			"Woodstock"
	};
	
	String[]district=new String[]{
			"CzechVillage",
			"FortBraggUnifiedSchoolDistrict",
			"IllinoisMedicalDistrict",
			"KingstonVillage",
			"NewBohemia",
			"ProfessorvilleHistoricDistrict"
	};
	
}
